-- Harmony claim portal schema. Applied by backend/deploy/deploy-backend.sh via
-- psql (idempotent: every statement uses IF NOT EXISTS).
--
-- Conventions
--   * amounts are atto-ONE integers stored as NUMERIC(78,0);
--   * secure_key is the lowercase 64-hex Keccak-256 of the 20-byte address,
--     stored WITHOUT the 0x prefix (source CSVs carry 0x; the injector strips it);
--   * address is the lowercase 0x-prefixed 40-hex address (null when the
--     preimage was never resolved);
--   * data tables (accounts, delegations, validator_vaults, routing_exceptions,
--     routing_destinations, snapshot_meta) are replaced atomically by the
--     injector through a staging-schema swap, so they carry no foreign keys.

CREATE TABLE IF NOT EXISTS schema_migrations (
  version    text PRIMARY KEY,
  applied_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS snapshot_meta (
  key   text PRIMARY KEY,
  value jsonb NOT NULL
);

CREATE TABLE IF NOT EXISTS accounts (
  secure_key                      char(64) PRIMARY KEY,
  address                         char(42) UNIQUE,
  address_resolved                boolean NOT NULL DEFAULT false,
  account_category                text NOT NULL
    CHECK (account_category IN ('ordinary_eoa', 'validator_account', 'contract', 'excluded')),
  code_bearing                    boolean NOT NULL DEFAULT false,
  contract_primary_category       text,
  liquid_shard0_atto              numeric(78,0) NOT NULL DEFAULT 0,
  liquid_shard1_atto              numeric(78,0) NOT NULL DEFAULT 0,
  active_staked_or_delegated_atto numeric(78,0) NOT NULL DEFAULT 0,
  pending_undelegation_atto       numeric(78,0) NOT NULL DEFAULT 0,
  unclaimed_staking_reward_atto   numeric(78,0) NOT NULL DEFAULT 0,
  pending_cross_shard_atto        numeric(78,0) NOT NULL DEFAULT 0,
  wallet_airdrop_atto             numeric(78,0) NOT NULL DEFAULT 0,
  staked_to_vault_atto            numeric(78,0) NOT NULL DEFAULT 0,
  total_claim_atto                numeric(78,0) NOT NULL DEFAULT 0,
  meets_threshold                 boolean NOT NULL DEFAULT false,
  nonce_shard0                    bigint,
  nonce_shard1                    bigint,
  code_hash_shard0                char(66),
  code_hash_shard1                char(66),
  last_activity_time_utc          timestamptz,
  last_activity_timestamp_unix    bigint,
  last_activity_block             bigint,
  last_activity_shard             smallint,
  last_activity_type              text,
  last_activity_tx_hash           char(66),
  last_activity_index             integer,
  last_activity_detail            text
);
CREATE INDEX IF NOT EXISTS accounts_address_lower_idx ON accounts (lower(address));

CREATE TABLE IF NOT EXISTS delegations (
  validator_address    char(42) NOT NULL,
  delegator_address    char(42) NOT NULL,
  staked_to_vault_atto numeric(78,0) NOT NULL,
  is_self_delegation   boolean NOT NULL DEFAULT false,
  priority             boolean NOT NULL DEFAULT false,
  PRIMARY KEY (validator_address, delegator_address)
);
CREATE INDEX IF NOT EXISTS delegations_delegator_idx ON delegations (delegator_address);

CREATE TABLE IF NOT EXISTS validator_vaults (
  validator_address              char(42) PRIMARY KEY,
  vault_assets_atto              numeric(78,0) NOT NULL DEFAULT 0,
  priority_staked_to_vault_atto  numeric(78,0) NOT NULL DEFAULT 0,
  deferred_staked_to_vault_atto  numeric(78,0) NOT NULL DEFAULT 0,
  delegation_rows                integer NOT NULL DEFAULT 0,
  governor_destination_id        text,
  governor_status                text NOT NULL DEFAULT 'ready',
  validator_name                 text
);

CREATE TABLE IF NOT EXISTS routing_exceptions (
  -- identity (not serial) so that CREATE TABLE ... (LIKE ... INCLUDING ALL) in
  -- the injector's staging schema gets its own sequence
  id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  component           text NOT NULL CHECK (component IN ('wallet_airdrop', 'vault_shares')),
  source_address      char(42) NOT NULL,
  source_category     text NOT NULL,
  validator_address   char(42),
  amount_atto         numeric(78,0) NOT NULL,
  exception_type      text NOT NULL,
  route_id            text NOT NULL,
  route_priority      bigint NOT NULL,
  destination_id      text,
  destination_address char(42),
  destination_status  text NOT NULL CHECK (destination_status IN ('ready', 'hold', 'not_issuing')),
  reason              text NOT NULL DEFAULT '',
  evidence            text NOT NULL DEFAULT ''
);
CREATE INDEX IF NOT EXISTS routing_exceptions_source_idx ON routing_exceptions (source_address);

CREATE TABLE IF NOT EXISTS routing_destinations (
  destination_id      text PRIMARY KEY,
  destination_address char(42),
  status              text NOT NULL,
  notes               text NOT NULL DEFAULT ''
);

CREATE TABLE IF NOT EXISTS reason_texts (
  reason_code text PRIMARY KEY,
  title       text NOT NULL,
  user_text   text NOT NULL
);

CREATE TABLE IF NOT EXISTS load_runs (
  id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  started_at   timestamptz NOT NULL,
  finished_at  timestamptz,
  data_version text NOT NULL,
  inputs       jsonb NOT NULL DEFAULT '{}'::jsonb,
  row_counts   jsonb NOT NULL DEFAULT '{}'::jsonb
);

INSERT INTO schema_migrations (version) VALUES ('001_schema')
ON CONFLICT (version) DO NOTHING;
