-- Next-batch confirmation evidence. These tables live in schema confirm so the
-- claim injector, which swaps only public data tables, cannot replace them.
-- The confirm API role receives its grants from db/ops/grants.sql, not here:
-- this migration runs as the table owner and does not grant runtime privileges.

CREATE SCHEMA IF NOT EXISTS confirm;

CREATE TABLE IF NOT EXISTS confirm.candidates (
  address            char(42) PRIMARY KEY,
  account_category   text NOT NULL CHECK (account_category IN ('ordinary_eoa', 'validator_account')),
  stage_reason       text NOT NULL CHECK (stage_reason IN (
                       'wallet activity predates initial window',
                       'no indexed wallet activity'
                     )),
  data_version       text NOT NULL CHECK (data_version !~ '[[:cntrl:]]' AND length(data_version) BETWEEN 1 AND 80),
  policy_version     text NOT NULL CHECK (policy_version !~ '[[:cntrl:]]' AND length(policy_version) BETWEEN 1 AND 80),
  cutoff_time_utc    timestamptz NOT NULL,
  loaded_at          timestamptz NOT NULL DEFAULT now()
);

-- Challenges are not stored. A confirmation request carries a random nonce and
-- an issued time; the server rebuilds the signed message from the candidate row.

CREATE TABLE IF NOT EXISTS confirm.confirmations (
  id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  address          char(42) NOT NULL,
  data_version     text NOT NULL,
  policy_version   text NOT NULL,
  stage_reason     text NOT NULL,
  message          text NOT NULL,
  signature        text NOT NULL CHECK (signature ~ '^0x[0-9a-fA-F]{130}$'),
  signer           char(42) NOT NULL,
  created_at       timestamptz NOT NULL DEFAULT now(),
  UNIQUE (address, data_version, policy_version)
);

-- Written by the owner role from db/ops/record-review.sh. The confirm API
-- role is not granted access.
CREATE TABLE IF NOT EXISTS confirm.reviews (
  id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  confirmation_id   bigint NOT NULL REFERENCES confirm.confirmations (id),
  status            text NOT NULL CHECK (status IN ('queued', 'included', 'rejected')),
  batch_id          text,
  note              text NOT NULL DEFAULT '',
  reviewed_at       timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS confirm.candidate_loads (
  id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  data_version      text NOT NULL,
  policy_version    text NOT NULL,
  cutoff_time_utc   timestamptz NOT NULL,
  row_count         integer NOT NULL,
  sha256            text NOT NULL,
  loaded_at         timestamptz NOT NULL DEFAULT now()
);

INSERT INTO schema_migrations (version) VALUES ('005_confirm_schema')
ON CONFLICT (version) DO NOTHING;
